### ISSUE TITLE
CI/CD Brigade Failure

### ISSUE THREAD

**Issue by snpdev** [Azure/blackbelt-aks-hackfest#76]
Two of us at SNP (@jayachandralingam and I) independently completed the CI/CD Brigade lab, but in the end our web apps did not update.

We could see the Brigade worker and jobs running and the webhook invoked in GitHub. We installed Kashti to get better visibility into the Brigade builds. In the Kashti dashboard we see the GitHub events for the project, but each in a failed state. In the Build page, it reads "There are currently no jobs inside this build."

Any thoughts as to what may be the cause?

**Comment by chzbrgr71** [comment]
There are a few places this can go wrong. It would be good to know what happened for you in case we can improve the instructions. 

Since your worker was running, we know the webhook must be configured correctly. Set aside Kashti for now to narrow our scope. 

Make sure you completed the Prerequisites. 

Do you see job-runners for both docker and k8s? It would be best to see the logs for the job runner pods. You can run `kubectl get pod --show-all` to see pods that completed. 

Then get logs by something like `kubectl logs job-runner-docker-1518560137098-ea5163b9`

You should see clues in these job runners where something like have gone wrong. It is possible that the ACR repo wasn't set in the `brigade.js`, but hopefully your logs tell us what is going on.

**Comment by snpdev** [comment]
Thanks Brian. I deleted my cluster RG earlier in the day, but I can see the ACR repo is set in my ```brigade.js```. 

Jaya's cluster is still running and there is no ```job-runner-docker-xxxxx``` pod. I don't have access to his forked repo to check ```brigade.js```.  I'll ask him to follow up.

**Comment by chzbrgr71** [comment]
You should check the logs on the worker pods and see what they say. This will show if there are errors in the `brigade.js`

**Comment by snpdev** [comment]
The log output:
```
$ kubectl logs brigade-worker-01c7m6502f226rhr2fnzd2zqb5
prestart: src/brigade.js written
[brigade] brigade-worker version: 0.10.0
[brigade:k8s] Creating PVC named brigade-worker-01c7m6502f226rhr2fnzd2zqb5
[brigade:app]   TypeError: Cannot read property 'substr' of undefined

  - brigade.js:12 EventRegistry.events.on
    ./dist/brigade.js:12:50

  - events.js:81 EventRegistry.fire
    ./dist/events.js:81:14

  - brigadier.js:34 Object.fire
    ./dist/brigadier.js:34:20

  - app.js:141 loadProject.then.then
    ./dist/app.js:141:23


[brigade:app] error handler is cleaning up
[brigade:k8s] Destroying PVC named brigade-worker-01c7m6502f226rhr2fnzd2zqb5
error Command failed with exit code 1.
```
I presume that the ```TypeError``` corresponds to line 12 of ```brigade.js```, namely:
```
brigConfig.set("gitSHA", brigadeEvent.commit.substr(0,7))
```
Not having access to Jaya's repo, I'm not sure if this log output is helpful, or a red herring.

As soon as time permits, I'll start from scratch.

**Comment by kevingbb** [comment]
PR #83 will resolve this. There were some changes to how some of the Brigade Event properties are accessed in newer versions of Brigade.

**Comment by jayachandralingam** [comment]
#83 Worked for I completed the CI/CD lab successfully. Thanks a lot.
